### ISSUE TITLE
[emidust variable not cmorized]

### ISSUE THREAD

**Issue by DirkOlivie** [NorwegianClimateCentre/noresm2cmor#123]
**Describe the bug**
The field emidust (emission strenght of dust) is not available on ESGF, neither on nird (/projects/NS9034K/CMIP6) for NorESM2-LM.  The variable emidust is part of AERmon.  However, the original data (emidust is calculated as the sum of SFDST_A2 and SFDST_A3) exists in the cam.h0-files.

**To Reproduce**

**Expected behavior**
Would it be possible to also cmor-ize emidust?

**Screenshots**

**Additional context**

**Comment by YanchunHe** [comment]
There was a typo in column E of google sheet on this `emidust`, so that it looks missing in the model output.

This has been fixed, and will be cmorized in the next round (will start soon, will notify this by seperate mail) of cmorization for all the existing experiments and coming new experiments

Please refer to Issue #80
