### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by adagj** [NorwegianClimateCentre/noresm2cmor#166]
Hi,
**Describe the bug**
I'm not sure if "bug" is the correct tag, but the years 111 - 140 are missing in the
  cmorized data for NorESM2-MM abrupt-4xco2 simulation. Year 1-110 and year 141-150 are cmorized. 

**To Reproduce**
1. Go to '/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/abrupt-4xCO2/r1i1p1f1/Amon'
2. E.g. ls rsdt/gn/v20191108/
3. rsdt_Amon_NorESM2-MM_abrupt-4xCO2_r1i1p1f1_gn_000101-001012.nc
rsdt_Amon_NorESM2-MM_abrupt-4xCO2_r1i1p1f1_gn_001101-002012.nc
rsdt_Amon_NorESM2-MM_abrupt-4xCO2_r1i1p1f1_gn_002101-003012.nc
rsdt_Amon_NorESM2-MM_abrupt-4xCO2_r1i1p1f1_gn_003101-004012.nc
rsdt_Amon_NorESM2-MM_abrupt-4xCO2_r1i1p1f1_gn_004101-005012.nc
rsdt_Amon_NorESM2-MM_abrupt-4xCO2_r1i1p1f1_gn_005101-006012.nc
rsdt_Amon_NorESM2-MM_abrupt-4xCO2_r1i1p1f1_gn_006101-007012.nc
rsdt_Amon_NorESM2-MM_abrupt-4xCO2_r1i1p1f1_gn_007101-008012.nc
rsdt_Amon_NorESM2-MM_abrupt-4xCO2_r1i1p1f1_gn_008101-009012.nc
rsdt_Amon_NorESM2-MM_abrupt-4xCO2_r1i1p1f1_gn_010101-011012.nc
rsdt_Amon_NorESM2-MM_abrupt-4xCO2_r1i1p1f1_gn_014101-015012.nc

Best regards,
Ada

**Comment by YanchunHe** [comment]
Hi Ada, Yes, we are doing the cmorization for this now, so it is not finished yet. And we encountered errors for doing this, likely due to these experiments are stored on temporarily mounted disk /projects/NS9560K/FRAM

Please refer to Issue #141 for the status of the this experiment.

And also refer to Issue #140 for the discussion of the problem.

Yanchun
