### ISSUE TITLE
invalid json file

### ISSUE THREAD

**Issue by YanchunHe** [NorwegianClimateCentre/noresm2cmor#30]
from time to time, the noresm2cmor crashes and reports error open json file. In the log:
```
 
^[[2;31;47mC Traceback:
! In function: cmor_open_inpathFile
! called from: cmor_dataset_json
! ^[[0m
 
^[[1;31;47m!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Please validate JSON File!
! USE: http://jsonlint.com/
! Syntax Error in file: namelist_NFHISTnorpddmsbc_PAMIP_1p6_pdSST-futArcSIC_mem1-25_f19_mg17_20190819_ra.json
!  {
 
!
!!!!!!!!!!!!!!!!!!!!!!!!!^[[0m
 
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
noresm2cmor3       000000000055229A  for__signal_handl     Unknown  Unknown
libpthread-2.17.s  00002B67FC4245D0  Unknown               Unknown  Unknown
libc-2.17.so       00002B67FC6674D7  kill                  Unknown  Unknown
noresm2cmor3       00000000004E6774  Unknown               Unknown  Unknown
noresm2cmor3       00000000004E40D9  Unknown               Unknown  Unknown
noresm2cmor3       00000000004DDEF7  Unknown               Unknown  Unknown
noresm2cmor3       000000000046ABF9  Unknown               Unknown  Unknown
noresm2cmor3       00000000004661BE  Unknown               Unknown  Unknown
noresm2cmor3       00000000004BB55F  Unknown               Unknown  Unknown
noresm2cmor3       000000000040DE6E  Unknown               Unknown  Unknown
libc-2.17.so       00002B67FC6533D5  __libc_start_main     Unknown  Unknown
noresm2cmor3       000000000040DD69  Unknown               Unknown  Unknown
```

Usually, if restart the program again, it succeed without error.

This might directly related to the CMOR library. 

Maybe no fix is need, but just report if others also met this before.

**Comment by IngoBethke** [comment]
I have not account this problem myself. 

I wonder if it might be related that you processes multiple decades of the same simulation in parallel (which I assume you do). The noresm2cmor version you used does not include information of the period in the file name of the json namelist. So if you process multiple time periods in parallel then each process writes to the same file and then reads it out immediately after. While the writing and reading is very quick, it can potential cause trouble depending on the file locking policy of underlying file system.  

From commit https://github.com/NorwegianClimateCentre/noresm2cmor/commit/e98a35e115226c8fee5fb8ca4e5f0532d7b867cf the file name of the json namelist now includes start and end of the period that is cmor-ized in order to make parallel CMOR-ization more robust.

**Comment by YanchunHe** [comment]
It should be true that this is caused by conflict of parrallel processes.
