### ISSUE TITLE
[CMIP6 CMORization & ESGF-publication] omip1/omip2 experiments

### ISSUE THREAD

**Issue by YanchunHe** [NorwegianClimateCentre/noresm2cmor#33]
Would you please help with cmorising the following omip1/omip2 experiments? They are stored on NIRD at -

/tos-project1/NS2345K/noresm/cases/NOIIAOC20TR_T62_tn14_20190628/
/tos-project1/NS2345K/noresm/cases/NOIIAJRAOC20TR_TL319_tn14_20190710/

(c.guo)

**Comment by YanchunHe** [comment]
According to the google sheet file "NorESM2 CMIP6 experiments version 3", the model configuration is "NorESM2-OI-M".

However, this is not registered in CMIP6_CV.json file.

This has to be registered before I can do the cmorization.

**Comment by AleksiNummelin** [comment]
I think this should probably still go under NorESM2-LM, or at least there is OMIP registered under NorESM2-LM, and these are basically the corresponding OMIP simulations. I think it will probably just confusing to have one more model name.

**Comment by YanchunHe** [comment]
I can use NorESM2-LM, if you decide to do so.

**Comment by ChunchengGuo** [comment]
yes, I agree that it should be NorESM2-LM.

**Comment by YanchunHe** [comment]
Model years to be cmorized:
NOIIAOC20TR_T62_tn14_20190628 from 1700-2071  ?
NOIIAJRAOC20TR_TL319_tn14_20190710  1653 - 2018 ?

**Comment by AleksiNummelin** [comment]
I think it would be good to CMORize the whole dataset for both simulations, but for NOIIAOC20TR_T62_tn14_20190628 we should only submit the 5 first cycles i.e. 1700-2009 (inclusive) to ESGF. This is because the OMIP1 protocol is for 5 cycles of the 62 year CORE forcing, and we did the 6th cycle (2010-2071) to see how the physical variables equilibrate. However, for this period the biogeochemistry doesn't make too much sense because the CO2 is kept constant.

**Comment by YanchunHe** [comment]
Could you check if idlagelvl in output files during 1880-1889 are correct?
Because it always fail it comes to this part.
@AleksiNummelin @ChunchengGuo

**Comment by YanchunHe** [comment]
Links for the cmorized data are created under: /projects/NS9034K/CMIP6/OMIP/

But we are going to do the cmorization again with external icegridfile with correct LAT/LON(i,j) information. Then the above files (links) will be updated.

**Comment by ChunchengGuo** [comment]
> Could you check if idlagelvl in output files of omip1 (omip2 are OK) during 1880-1889 are correct?
> Because it always fail it comes to this part.
> @AleksiNummelin @ChunchengGuo

just identified the following file - NOIIAOC20TR_T62_tn14_20190628.micom.hm.1880-05.nc

a quick check with cdo and ncview - they work for all variables in this file except idlagelvl.  For example, "ncks -v idlagelvl /projects/NS2345K/noresm/cases/NOIIAOC20TR_T62_tn14_20190628/ocn/hist/NOIIAOC20TR_T62_tn14_20190628.micom.hm.1880-05.nc idlage_NOIIAOC20TR_T62_tn14_20190628.micom.hm.1880-05.nc" gives the following error -

nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_get_vara()
nco_err_exit(): ERROR Error code is -101. Translation into English with nc_strerror(-101) is "NetCDF: HDF error"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE) 

It could be because of damaged netcdf data? also cc. @monsieuralok @IngoBethke

**Comment by AleksiNummelin** [comment]
I checked and the NOIIAOC20TR_T62_tn14_20190628.micom.hm.1880-05.nc has corrupted idlagelvl file also on Vilje. I also talked with Mats, and the plan for now is the following: I will produce the ice grid file tomorrow, and we run the CMORization with OMIP first without the idlagelvl, while we wait for rerun of the model, how does that sound?

**Comment by AleksiNummelin** [comment]
I have now started a rerun to fix the problem with the 1880-05 file. It is sitting in the queue at the moment, but it should finish in less than a day once it starts. Once it is finished we can proceed with the CMORization, I will update this issue once it is done.

**Comment by AleksiNummelin** [comment]
@YanchunHe the corrupt file has now been replaced with a new file, please try to run the CMORization again and let me know if there are any further problems!

**Comment by YanchunHe** [comment]
I tried again. but talklvl during 1950-1959 for omip1 simualtion also has error:
NetCDF: HDF error
I guess this is the same error type.

1880-1889 is OK now.

**Comment by AleksiNummelin** [comment]
@YanchunHe, the file is updated, let me know again if further problems exist. I realized that the problem is that for few of the cases (restart periods) the time I gave to the archiving script was not enough it seems that sometimes this created corrupt files (I guess this depends on whether or not the script was in the middle of writing a file when it was killed), but not always. Anyhow, I think it is possible there are more such files.

**Comment by YanchunHe** [comment]
omip1 and omip2 are cmorized and ready to publish

**data path**

- /projects/NS9034K/CMIP6/OMIP/NCC/NorESM2-LM/omip1/r1i1p1f1
- /projects/NS9034K/CMIP6/OMIP/NCC/NorESM2-LM/omip2/r1i1p1f1

**version**
-v20190920

**other**
- PrePARE QC passed
- sha256sum updated

Please have a quick manual quality-check and confirm if it is OK to publish @AleksiNummelin 

commit:
3bdd5dd0633f123da03a08faac84c13d7a17e096
c095c413b7c2aeaa0372c27574369e388cca99e2

**Comment by AleksiNummelin** [comment]
Sorry about the delay, the data looks good, I didn't check all the variables but at least the tricky ones seem reasonable.

However, @YanchunHe and @monsieuralok, I wanted to point out that ideally, we should only publish the OMIP1 data until 2009, i,e. the 200001-200912 decade would be the last. The last omip cycle (2010-207112) was an extra cycle that we ran for the intercomparison study we are participating in. However, the biogeochemical variables don't make much sense for this cycle because the forcing ends (i.e. values are kept constant) after 2009 or so (actually I think it is slightly different for different files). However, for our own purposes it is very good to have the full dataset CMORized.

**Comment by YanchunHe** [comment]
OK, thanks! then @monsieuralok make sure only data til 200001-200912 for omip1 are included in the map files so that will be published.

**Comment by monsieuralok** [comment]
Hi, There is some problem with data set **_grKbCSh14126_** as it is failing to publish with message invalid value. Invalid value of mandatory field 'grid_label': grKbCSh14126, must be one of ['gm', 'gn', 'gna', 'gng', 'gnz', 'gr', 'gr1', 'gr1a', 'gr1g', 'gr1z', 'gr2', 'gr2a', 'gr2g', 'gr2z', 'gr3', 'gr3a', 'gr3g', 'gr3z', 'gr4', 'gr4a', 'gr4g', 'gr4z', 'gr5', 'gr5a', 'gr5g', 'gr5z', 'gr6', 'gr6a', 'gr6g', 'gr6z', 'gr7', 'gr7a', 'gr7g', 'gr7z', 'gr8', 'gr8a', 'gr8g', 'gr8z', 'gr9', 'gr9a', 'gr9g', 'gr9z', 'gra', 'grg', 'grz']

omip2 is already published.

**Comment by YanchunHe** [comment]
where is "grKbCSh14126"?

those files are typically intermediate files during cmorization, and should exclude from the publishing.

We should just simply remove them, and also from the .map and .sha256sum files.

**Comment by monsieuralok** [comment]
Hi, it is in file /projects/NS9034K/CMIP6/OMIP/NCC/NorESM2-LM/omip1/.r1i1p1f1.sha256sum
I will remove it then from my MAP file. 
Alok

**Comment by YanchunHe** [comment]
OK, thanks! I removed it from .sha256sum file, and will remove the data file.

but, could you hold on for the publish a bit?

Cos Jörg is thinking about some fix/updates to this and then publish.

I will let you know when it is ready.

**Comment by monsieuralok** [comment]
@YanchunHe I would wait for yours comment

**Comment by YanchunHe** [comment]
To do:
update chlos (wrong missing values) and add intpp

(requested by Jörg)
Please hold on the ESGF publish until this is done.

**Comment by YanchunHe** [comment]
chlos is updated and intpp is added, with version tag v20191022

Ready to publish

**data path**
- /projects/NS9034K/CMIP6/OMIP/NCC/NorESM2-LM/omip1/r1i1p1f1
- /projects/NS9034K/CMIP6/OMIP/NCC/NorESM2-LM/omip2/r1i1p1f1

**version**
- v20190920
- v20191022

@JorgSchwinger @monsieuralok

**Comment by monsieuralok** [comment]
@YanchunHe For OMIP2, variables intpp_Omon and chlos_Omon, there are 36 files and for variable fsitherm_Omon and most, there are 27 files. For variables with 27 files, data from 1660-1760 are missing. Variable with 36 files, data from 2000-2009 are missing. Is it OK or something missing?

**Comment by YanchunHe** [comment]
I will check with this!

**Comment by monsieuralok** [comment]
@YanchunHe omip1  and omip2 are having two version for variable chols in  

r1i1p1f1/Omon/chlos/gn/v20190920/chlos_Omon_NorESM2-LM_omip2_r1i1p1f1_gn_176001-176912.nc
r1i1p1f1/Omon/chlos/gn/v20191022/chlos_Omon_NorESM2-LM_omip2_r1i1p1f1_gn_176001-176912.nc

last one was published as I have not noticed before?  I guess that is we want.

**Comment by YanchunHe** [comment]
Yes, the 1022 version is correct, and should be published. The 0920 version is not perfect but not fatally wrong, that is why I did not delete since you may have published it.

In short, the last one (1022) should be published, but it is OK if both can reside on ESGF.

**Comment by monsieuralok** [comment]
@YanchunHe  @ChunchengGuo  @AleksiNummelin  published : - Only last one reside on the ESGF.

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
- /projects/NS9034K/CMIP6/OMIP/NCC/NorESM2-LM/omip1
- /projects/NS9034K/CMIP6/OMIP/NCC/NorESM2-LM/omip2 

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b
( two files of the same name)

**other information**
Please note, years 2010-207112 of omip1 should not be published (though they are cmorized and in the sha256sum file).

**Comment by monsieuralok** [comment]
@YanchunHe I have got new version of variable  intpp it means NEW one should take priority as time period seems to be same.. ?

**Comment by YanchunHe** [comment]
Yes, if newer version of the same variable exits, it will be used.

So it is OK if there are several versions even if they are actually identical.

**Comment by monsieuralok** [comment]
@YanchunHe @ChunchengGuo @AleksiNummelin published
