### ISSUE TITLE
wrong value of latitude/longitude in cmorized output

### ISSUE THREAD

**Issue by YanchunHe** [NorwegianClimateCentre/noresm2cmor#39]
In OMIP experiment,
LAT/LON data look right.
```
$ ncdump -v TLAT /projects/NS9560K/noresm/cases/N1850_f19_tn14_20190621/ice/hist/N1850_f19_tn14_20190621.cice.h.1600-01.nc
netcdf N1850_f19_tn14_20190621.cice.h.1600-01 {
dimensions:
        d2 = 2 ;
        ni = 360 ;
        nj = 384 ;
        nc = 5 ;
        nkice = 8 ;
        nksnow = 3 ;
        nkbio = 5 ;
        time = UNLIMITED ; // (1 currently)
        nvertices = 4 ;
variables:
        float time(time) ;
                time:long_name = "model time" ;
                time:units = "days since 0001-01-01 00:00:00" ;
                time:calendar = "noleap" ;
                time:bounds = "time_bounds" ;
        float time_bounds(time, d2) ;
                time_bounds:long_name = "boundaries for time-averaging interval" ;
                time_bounds:units = "days since 0001-01-01 00:00:00" ;
        float TLON(nj, ni) ;
                TLON:long_name = "T grid center longitude" ;
                TLON:units = "degrees_east" ;
                TLON:missing_value = 1.e+30f ;
                TLON:_FillValue = 1.e+30f ;
                TLON:bounds = "lont_bounds" ;
        float TLAT(nj, ni) ;
                TLAT:long_name = "T grid center latitude" ;
                TLAT:units = "degrees_north" ;
                TLAT:missing_value = 1.e+30f ;
                TLAT:_FillValue = 1.e+30f ;
                TLAT:bounds = "latt_bounds" ;
...
...
    76.66061, 76.33442, 76.00912, 75.68472, 75.36127, 75.0388, 74.71732,
    74.39686, 74.07745, 73.75912, 73.44192, 73.12584, 72.81094, 72.49724,
    72.18477, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ ;
}
```

But in cmorized output, for example,
```
$ncdump -v latitude /scratch/yanchun/cmorout/NorESM2-LM/omip1/v20190920/siage_SImon_NorESM2-LM_omip1_r1i1p1f1_gn_170001-170012.nc
netcdf siage_SImon_NorESM2-LM_omip1_r1i1p1f1_gn_170001-170012 {
dimensions:
        time = UNLIMITED ; // (12 currently)
        j = 384 ;
        i = 360 ;
        bnds = 2 ;
        vertices = 4 ;
variables:
        double time(time) ;
                time:bounds = "time_bnds" ;
                time:units = "days since 0001-01-01 00:00:00" ;
                time:calendar = "noleap" ;
                time:axis = "T" ;
                time:long_name = "time" ;
                time:standard_name = "time" ;
        double time_bnds(time, bnds) ;
        int j(j) ;
                j:units = "1" ;
                j:long_name = "cell index along second dimension" ;
        int i(i) ;
                i:units = "1" ;
                i:long_name = "cell index along first dimension" ;
        double latitude(j, i) ;
                latitude:standard_name = "latitude" ;
                latitude:long_name = "latitude" ;
                latitude:units = "degrees_north" ;
                latitude:missing_value = 1.e+20 ;
                latitude:_FillValue = 1.e+20 ;
                latitude:bounds = "vertices_latitude" ;
        double longitude(j, i) ;
                longitude:standard_name = "longitude" ;
                longitude:long_name = "longitude" ;
                longitude:units = "degrees_east" ;
                longitude:missing_value = 1.e+20 ;
                longitude:_FillValue = 1.e+20 ;
                longitude:bounds = "vertices_longitude" ;
...
    67.3815460205078, 67.0956344604492, 66.8116760253906, 66.5297241210938,
    66.2498397827148, 65.9720764160156, 1.00000001504747e+30,
    1.00000001504747e+30, 1.00000001504747e+30, 1.00000001504747e+30,
    1.00000001504747e+30, 1.00000001504747e+30, 1.00000001504747e+30,
    1.00000001504747e+30, 1.00000001504747e+30, 1.00000001504747e+30,
    1.00000001504747e+30, 1.00000001504747e+30, 1.00000001504747e+30,
    1.00000001504747e+30, 1.00000001504747e+30 ;
}
```

The _FillValue/missing value are not recognised correctly.

**Comment by IngoBethke** [comment]
Ideally, coordinate variables should not have any missing values which is also not the case for the gx1 grid. 

In any case, the place to modify is in read_gridinfo_ifile in m_modelsice.F. E.g. you could try setting all values with exceeding 1e20 to 1e20. This might fix it (or at least hide) the problem.

**Comment by YanchunHe** [comment]
set undefined latitude/longitude points to _FillValue (1e20)in cmorized output
However, please the CMOR will still report warning message during runtime, since the _FillValue (1e20) is obviously beyond the valid range (-90 to 90).
commit 5a37b78

**Comment by IngoBethke** [comment]
As I already mentioned, there shouldn't be undefined coordinate values. So I agree with the cmor warning.

**Comment by YanchunHe** [comment]
Yes, I know. I just made a note above that it still has warning (as expected), but the actual value in the cmorized output is correct now. I close the issue.

**Comment by AleksiNummelin** [comment]
Just wanted to comment here (for some reason) CICE seems to map the atmospheric (?) land/mask on the coordinate variables. I think the solution here is acceptable, another option could be to read in the actual binary grid file, but that seems like an unnecessary hassle. However, I was wondering if the lat/lon info should be carried also in the CMORized output. Don't we provide a grid file where this info is anyway?

**Comment by YanchunHe** [comment]
Please check if cmorized files seem all right under (in progress now so don't look at the newest temporary files) : 
/projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/omip1/v20190923

btw, PrePARE Quality-check passes without error.

**Comment by IngoBethke** [comment]
Thanks for the clarification, Aleksi. 

It is unfortunate that the coordinate values are masked and I'm concerned that this will create trouble for some users. Note also that the cmor-tool guesses grid cell corner information from neighbouring points and this information is likely affected as well. 

The cmor-ization tool reads the coordinate information of the sea ice component from the output files. It is not read from the grid file directly primarily because that one uses machine binary format and not NetCDF. Of course , it is possible to read machine binary but on expense of portability of the cmor-ization tool (e.g. it would require compiler specific options for endianness) and it would take some time to implement it. Probably better, one could create a sea ice grid-file in netcdf format and read that one in. But I will have to focus on the NorCPM1 DCPP output (which is not subject to the problem) and therefore won't have to fix it.

**Comment by IngoBethke** [comment]
Follow up to my last comment: 

One solution could be to introduce an "icegridfile" namelist entry (like for the ocean and atmosphere component). If set, read the coordinate information from the file specified in the entry and if not set, read the coordinate information from the history output as currently done. To generate the netcdf grid file the easiest would be to extract the coordinate information from the history output of a coupled simulation.

**Comment by AleksiNummelin** [comment]
I thought we would actually do this anyway (i.e. provide a grid file for ocn, atm, ice components), but I guess we didn't do it for the ice in CMIP5. Anyway, I can maybe look into it because I think that would be definitely the cleanest solution.

**Comment by IngoBethke** [comment]
Sounds good. 

The reading of sea ice coordinate information is done in read_gridinfo_ifile (line 612) in https://github.com/NorwegianClimateCentre/noresm2cmor/blob/master/source/m_modelsice.F 

The fields read are TLON, TLAT, ULON, ULAT and ANGLE.

The handling of the input namelists is done in  https://github.com/NorwegianClimateCentre/noresm2cmor/blob/master/source/m_namelists.F

**Comment by YanchunHe** [comment]
Can you directly overwrite the latitude/longitude in the cmorized output file? Is that allowed by CMOR library quality-check?
Then I don't need to recmorized all the files, but only to calculate the sha256sum.

**Comment by AleksiNummelin** [comment]
Not sure about that, I think we should just go with the approach here and try to produce an ice grid file. In the end, the coordinates should be the same, just without the mask, so I don't think there should be a need to rerun anything.

**Comment by YanchunHe** [comment]
My understanding is Ingo suggest create a separate ice grid file, read the lat/lon information from this grid file (if available) instead of reading from data file.

Reply to Ingo: yes, I can redo the cmorization if this is the best solution.

**Comment by AleksiNummelin** [comment]
I had a look at it seems that the problem is there also in coupled simulations. I will try to create the grid file by reading the original grid binary file to recover ULAT, ULON, whereas the TLON, TLAT we can get from the MICOM grid file (same as PLON,PLAT).

**Comment by YanchunHe** [comment]
Can we just replace the ULAT/ULON, TLAT/TLON etc in the original model output with the correct values? using tools like nco?

This is simplest solution as I can see.

**Comment by IngoBethke** [comment]
Aleksi is right, the problem seems to be present in all our published NorESM2 sea ice output (just checked the historical output). So it is not OMIP specific. 

I guess it makes sense to proceed with OMIP publication including this cosmetic error and place a note on the errata pages https://errata.es-doc.org/static/index.html with status set to "WONT FIX". At a later time, you can still decide to fix and re-publish.

Otherwise you may as well stop all further publication of NorESM2 output that is subject to the issue and re-cmorize and re-publish all already published sea ice output. This would be a major undertaking and significantly delay CMIP6 publication.

**Comment by AleksiNummelin** [comment]
As Ingo mentioned, I think it is best to proceed with the 'error'. I will (try to) create that ice grid file anyway, so maybe we can find a way to publish that at later stage (or if not then at least we have that for future purposes). We should also figure out where this is happening, I had a quick look at the cice code, but not entirely sure if it is happening there.

**Comment by YanchunHe** [comment]
This error are not fixed in the cmorzied  in the cmorized data but get disregarded.
close the issue now.

**Comment by OskarMETNO** [comment]
I have now found the same problem with the sea ice grid (at least for siconc on both SIday and SImon):
![image](https://user-images.githubusercontent.com/10518039/74349556-b2f3de00-4db4-11ea-945a-30b70d9b8fa8.png)
Left is siconc (on sea ice grid), right is tos (on ocean grid).

This creates problem when interpolating to another grid. The quick-fix for me would have been to copy the longitude and latitude data from an ocean variable (e.g. tos), but it turns out the dimensions are actually not the same:
` siconc:     j = 384 ;     i = 360 ; # (sea ice grid)`
` tos:         j = 385 ;     i = 360 ; # (ocean grid)`
I suspected that it was just an extra row, so that values for j=1:384 and i=1:360 would be identical, but when comparing the longitude (or latitude) values it seems they are off by small values (1E-14 to 1E-6), e.g.
` tos_lon[121,102] - siconc_lon[121,102] => 2.842171e-14 `
` tos_lat[236,361] - siconc_lat[236,361] => 9.971866e-05 `

I see the point from Ingo that we should not edit the CMORized files in the archive. Have you already solved this by saving longitude and latitude in a separate file? If so, is it available somewhere?

**Comment by AleksiNummelin** [comment]
Hi @OskarMETNO , yes, this error is present in all of the CMIP6 output, and no, I have not created a separate file with lat/lon info. Anyhow, in principle, the ocean grid has simply an extra row i.e the quick fix is to do what you suggest. If you dive into the details, it is true that the lat/lon info is not exactly the same on the CICE and BLOM output even if they technically run on the same grid. If I remember correctly, this is due to the way CICE calculates the grid point center vs the way BLOM calculates the grid point center. 

I remember having some discussions about this with @IngoBethke and possibly with Mats some years back. I can't remember the details but somehow I think there were arguments for the BLOM way being the 'more correct' approach. In any case, these details should not matter for regridding (I would suggest doing any budget calculations on the natural grid), and if you want to be super safe, then you could just replace the masked values with those from the ocean grid. Unless you regrid to a very coarse grid, the lat/lon points taken from the ocean grid will end up under the land mask and will not affect the regridded fields.

**Comment by OskarMETNO** [comment]
Thanks a lot Aleksi for the fast and detailed reply! Then I will use the coordinate values from tos.

**Comment by YanchunHe** [comment]
Good, and thanks to @AleksiNummelin for the reply!
