### ISSUE TITLE
branch_time_in_parent format in json file

### ISSUE THREAD

**Issue by YanchunHe** [NorwegianClimateCentre/noresm2cmor#40]
When an experiment has no parent, the branch_time_in_parent should be omitted (or set to 0.0D0).

`CALL json%add(p,'branch_time_in_parent',branch_time_in_parent)`

write the value of branch_time_in_parent in *.json file as 0.0E0

However, in CMOR library Src/cmor_CV.c
```
            if (cmor_has_cur_dataset_attribute(BRANCH_TIME_IN_PARENT) == 0) {
                cmor_get_cur_dataset_attribute(BRANCH_TIME_IN_PARENT, szValue);
                if (strcmp(szValue, "0.0") != 0) {
                    snprintf(msg, CMOR_MAX_STRING,
                             "Your input attribute %s %s \n! "
                             "has been replaced with 0.0 \n! ",
                             BRANCH_TIME_IN_PARENT, szValue);
                    cmor_set_cur_dataset_attribute_internal
                      (BRANCH_TIME_IN_PARENT, "0.0", 1);

                    cmor_handle_error(msg, CMOR_WARNING);
                }
            }
```
It is compared is the value of the string branch_time_in_parent read from the json file equals "0.0" instead of 0.0E0.

As a result, noresm2cmor tool (more accurate CMOR library), will report a warning.

@IngoBethke Could you change the format of the branch_time_in_parent when it is written to json file? That is to say, change from e.g, ES6.1E1 to F3.1?

I don't find where to change this in the json_*.F90 files.

**Comment by IngoBethke** [comment]
I'm not sure about your request. 

The "branch_time" entry is written as numerical and not string to the json-file (note that the latest commit dumps the json file to the standard out/log before deleting it). 

You can change it in m_namelist.F in write_namelist_json by specifying a string instead of a numerical value for branch_time but I'm not sure whether the cmor-library accepts it (in CMIP6_input_example.json it is also numerical).

I had a quick look at the json fortran library and can't see that it is possible to influence the format of numericals.  

Since this is a cosmetic issue I cannot further prioritise it.

**Comment by YanchunHe** [comment]
<img width="705" alt="Screenshot 2019-09-23 at 14 35 52" src="https://user-images.githubusercontent.com/1725351/65425942-7cbabf80-de0f-11e9-98f4-e84863502ed4.png">

**Comment by YanchunHe** [comment]
This only effects the experiment with no parent. It is not critical.
I noticed ` CALL json%add(p,'branch_time_in_parent',branch_time_in_parent)`
but see no where to specify the format.
may need look into those json_*.F90 files.
I leave it as it is and close the issue now.
