### ISSUE TITLE
[CMIP6 CMORization & ESGF-publication] CMORization of the first RFMIP-SpAer experiment (30 years, fSST)

### ISSUE THREAD

**Issue by Kirkevag** [NorwegianClimateCentre/noresm2cmor#44]
The first RFMIP-SpAer experiment piClim-SpAer-aer is finalized with output stored on nird at

/projects/NS9560K/noresm/cases/piClim-SpAer2014

The MIP leader request CMORized data as quickly as possible (orignal deadline was end of September), CMORIzed, but not necessarily put on ESGF. Could this be given some priority?
Although the upcoming historical counterpart is more important (Tier 1), this grants  us contribution in an important manuscript for IPCC AR6. This is separate from the main/standard RFMIP study/manuscript.

Since the aerosol optics and cloud droplet number concentrations (CDNC) are s mix between CAM6-Oslo (for 1850 aerosol emissions) and prescribed optical properties and CDNC (anthropogenic contribution after 1850 is prescribed based on the MACv2-SP code from Stevens et al.), there is some additional specialized output (like instantaneous rdiative forcing) which is calculated only for this model set-up (run with define SPAERO), which I cannot even find listed in the CMIP6 data request google sheet. But I suggest to run CMOR as normal, and handle these specialized output separately, when we have more information about what and on what form(at) exactly this should be submitted. If someone knows anything about the details of this (Yanchun?). please let me (Alf) know.

**Comment by YanchunHe** [comment]
## Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases/piClim-SpAer2014

**experiment_id**
piClim-SpAer-aer

**CASENAME(s) and years to be CMORized**
piClim-SpAer2014, 1-30

## Optional information

(additional information, if the experiment is branched/hybrid restart from previous parent experiment)

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1

**parent_time_units**
'days since 0421-01-01'

**branch_method**
'Hybrid-restart from year 1600-01-01 of piControl',

**other information**
(provide other information that might be useful)
...

**Comment by Kirkevag** [comment]
Under "other information", I can add that the code and scheme used in RFMIP-SpAer is described in some detail at 
https://github.com/metno/noresm-dev/issues/15

**Comment by Kirkevag** [comment]
Correction of the above: Hybrid-restart from year 1600-01-01 of piControl

**Comment by YanchunHe** [comment]
Please grant read access to all the folders:
/projects/NS9560K/noresm/cases/piClim-SpAer2014/*/

**Comment by Kirkevag** [comment]
What is the best recursive command to use for this?

**Comment by YanchunHe** [comment]
CMORization finished. Ready to publish to ESGF.
Also refer to #50

**Comment by monsieuralok** [comment]
@YanchunHe Published
