### ISSUE TITLE
[CMIP6 CMORization & ESGF-publication] piControl - NorESM1-F

### ISSUE THREAD

**Issue by ChunchengGuo** [NorwegianClimateCentre/noresm2cmor#48]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS2345K/noresm/cases

**experiment_id**
piControl

**CASENAME(s) and years to be CMORized**
NBF1850OC_f19_tn11_02, 1501-1700

### Optional information
none

**parent_experiment_id**
no parent

**parent_experiment_rip**
r1i1p1

**parent_time_units**
no parent

**branch_method**
none

**other information**
none

**Comment by IngoBethke** [comment]
Modified the issue to include ESGF-publication

**Comment by YanchunHe** [comment]
piControl should have a parent_experiment, according to CMIP6_CV.json

Therefore, the following setting are defined to avoid warnings/errors:

parent_experiment_id  = 'piControl-spinup',
parent_experiment_rip = 'r1i1p1',
parent_time_units = 'days since 0001-01-01',
branch_method = 'No piControl-spinup',

**Comment by YanchunHe** [comment]
According #46 , you have 1000 year spinup as "piControl-spinup"

So specify the time units in your spinup, and how this is branched, e.g., "hybrid-restart from year 1001-01-01 of piControl-spinup'

Specify the full path to your piControl-spinup, so that I may have a look at it sometimes for some information.

**Comment by ChunchengGuo** [comment]
I'm not sure if the piControl is "hybrid-restart from year 1001-01-01 of piControl-spinup' - it is just a continuation of the 1000-year long piControl-spinup. Is this info important? and how should I understand the "time units" under the context here?

The full path to piControl-spinup is here - /projects/NS2345K/noresm/cases/NBF1850OC_f19_tn11_01

**Comment by YanchunHe** [comment]
Then NBF1850OC_f19_tn11_01 is parent experiment with experiment id "piControl-spinup'
Since you changed the model time, it is likely you use 'hybrid restart'.

Therefore, I define the following settings:
parent_experiment_id = 'piControl-spinup',
parent_experiment_rip = 'r1i1p1',
parent_time_units = 'days since 0001-01-01',
branch_method = 'hybrid-restart from year 1001-01-01 of piControl-spinup',

This might not be cruise, but necessary to define another two varialbes:
 branch_time_in_child   = 547500.0D0,
 branch_time_in_parent  = 365000.0D0,
which define the time when the model starts and when it is branched from its parent.

One can find more information about ["CMIP6 Global Attributes, DRS, Filenames, Directory Structure, and CV’s"](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit)

Will start the cmorization soon based on above information

**Comment by YanchunHe** [comment]
piControl NorESM1-F is cmorized and ready to publish

**data path**
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM1-F/piControl/r1i1p1f1

**version**
-v20190920

**other**
- PrePARE QC passed
- sha256sum updated

**Comment by YanchunHe** [comment]
The following fields are not available in piControl:

- sfdsi_Omon
- sidmassgrowthbot_SImon
- sidmassgrowthwat_SImon
- sidmassmeltbot_SImon
- sidmassmelttop_SImon

so that they are also excluded from other counterpart experiments:

- lig127k #46 
- midHolocene #56 
- midPliocene-eoi400 #57 

Namelist commits for piControl:
- 87eb1bbf28c4b09690b6b00d9fb2329ff9d768a4
- a770c5046c8a66dd27de110da85e29a6c3141f18

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
- /tos-project1/NS9034K/CMIP6/CMIP/NCC/NorESM1-F/piControl

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@YanchunHe @ChunchengGuo finished
